### ISSUE TITLE
Bibliography partially loaded and PDF annotation imported

### ISSUE THREAD

**Issue by Michael-ljn** [krassowski/jupyterlab-citation-manager#59]
The extension is amazing but I'm facing a weird issue. I made sure my API was on “read-only” and that only “library access” was allowed. But when using the extension to cite a paper, I can retrieve only a very few of them and a bunch of annotations from some pdf files.

**Comment by krassowski** [comment]
Thank you. I think this might be the same issue that we saw in #44. I will have another look next week.

**Comment by krassowski** [comment]
The relevant code is in:

https://github.com/krassowski/jupyterlab-citation-manager/blob/6fd14d31d7572725b5ac372cc42adc40d4185b6e/src/zotero.ts#L358-L428

**Comment by letaltom** [comment]
I have the same problem, 808 items in Zotero, but JupyterLab fetches only 300 citable items

**Comment by bsdz** [comment]
I think the issue lies in the line below. The global counter is incremented by the page start index each time, so if we have 25 items in each index, then the start index will be 25, 50, 75 etc. Summing all these will be 25\*n(n+1)/2. 

In my case I have 1146 citations and I am downloading 250 citations which happens to be 25\*ceil(-1/2 + sqrt((1/2)^2 + 2\*1146/25)).

Similarly, in issue #44 note that 25\*ceil(-1/2 + sqrt((1/2)^2 + 2\*1146/25)) = 875.

I think the solution might be some a case of replace the line:

https://github.com/krassowski/jupyterlab-citation-manager/blob/6fd14d31d7572725b5ac372cc42adc40d4185b6e/src/zotero.ts#L395

with something like:

```typescript
i = parseInt(nextParams.start, 10); 
```

I'd raise a PR but not in a position to test it.

**Comment by krassowski** [comment]
Thank you! I have released v0.3.2 including the fix from #61.
